name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    uses: SpencerRWood/workflows/.github/workflows/release.yml@v1
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      dbt_host: ${{ secrets.DBT_HOST }}
      dbt_port: ${{ secrets.DBT_PORT }}
      dbt_user: ${{ secrets.DBT_USER }}
      dbt_password: ${{ secrets.DBT_PASSWORD }}
      dbt_dbname: ${{ secrets.DBT_DBNAME }}
      dbt_schema: ${{ secrets.DBT_SCHEMA }}
